image:
  file: .gitpod.Dockerfile

tasks:
  - name: Ready
    command: echo "Workspace ready!"

vscode:
  extensions:
    - hashicorp.terraform
    - ms-vscode.vscode-typescript-next
    - redhat.vscode-yaml
